(TimeCmd (ShowCmd (IntExpr 6)))
(TimeCmd (ShowCmd (FloatExpr 0)))
(WriteImageCmd (FloatExpr 65974558930474) "")
(WriteImageCmd (FloatExpr 0) "")
(ShowCmd (IntExpr 534))
(ReadImageCmd "" (VarArgument e))
(PrintCmd "")
(StmtCmd (LetStmt (ArgLValue (VarArgument Q)) (CallExpr y1w_)))
(PrintCmd "/")
(WriteImageCmd (IntExpr 53) "4Ub ")
(ReadImageCmd "" (VarArgument O3c_0q.8f_))
(ReadImageCmd "" (VarArgument U))
