(ShowCmd (IntExpr 3))
(ShowCmd (IntExpr 6773))
(PrintCmd "")
(PrintCmd ".%")
(ShowCmd (VarExpr o2o_))
(WriteImageCmd (IntExpr 9) "t_")
(ReadImageCmd "" (VarArgument Z))
(WriteImageCmd (FloatExpr 0) "")
(WriteImageCmd (CallExpr b1G_2b.3p_) "")
(ReadImageCmd "" (VarArgument Y))
(StmtCmd (AssertStmt (VarExpr L0s.9c.4u_0f.) "M@"))
(TimeCmd (ShowCmd (IntExpr 7)))
