(StmtCmd (LetStmt (ArgLValue (VarArgument e)) (FloatExpr 53)))
(StmtCmd (AssertStmt (IntExpr 63) "r|J"))
(WriteImageCmd (CallExpr O (VarExpr A) (VarExpr y1L.2j.) (VarExpr g)) "9I")
(StmtCmd (LetStmt (ArgLValue (VarArgument b8t_0B.)) (FloatExpr 0)))
(WriteImageCmd (CallExpr Z9z_4u_1X.5B. (CallExpr w2x_8F_1W.)) "")
(ShowCmd (VarExpr y))
(ReadImageCmd "" (VarArgument C))
(PrintCmd "U")
(ShowCmd (VarExpr P8N.))
(TimeCmd (WriteImageCmd (CallExpr o) "`,"))
(ReadImageCmd "" (VarArgument u))
(ReadImageCmd "N" (VarArgument N5L_7w_5d_))
(WriteImageCmd (FloatExpr 0) "")
