(ShowCmd (FloatExpr 0))
(TimeCmd (ReadImageCmd "" (VarArgument Z)))
(PrintCmd "")
(WriteImageCmd (FloatExpr 70) "TXM'")
(ReadImageCmd "5p" (VarArgument A))
(StmtCmd (LetStmt (ArgLValue (VarArgument J)) (FloatExpr 0)))
(StmtCmd (AssertStmt (VarExpr o) "mh"))
(ReadImageCmd "I0[gWX" (VarArgument v5Q.))
(TimeCmd (ShowCmd (VarExpr M2Z.)))
(ReadImageCmd "" (VarArgument H))
(StmtCmd (LetStmt (ArgLValue (VarArgument n)) (VarExpr N)))
