(TimeCmd (ShowCmd (IntExpr 8)))
(StmtCmd (AssertStmt (IntExpr 0) "C"))
(TimeCmd (StmtCmd (ReturnStmt (CallExpr w5V_))))
(WriteImageCmd (IntExpr 130) "b")
(ShowCmd (VarExpr z))
(TimeCmd (TimeCmd (ShowCmd (FloatExpr 0))))
(TimeCmd (StmtCmd (ReturnStmt (VarExpr n))))
(ReadImageCmd "" (VarArgument i3A_1Z.0f_1h.))
(PrintCmd "b")
(PrintCmd "N")
(WriteImageCmd (FloatExpr 0) "")
(WriteImageCmd (CallExpr I9s_5R_) "M")
(PrintCmd "")
