(StmtCmd (LetStmt (ArgLValue (VarArgument k)) (IntExpr 753)))
(StmtCmd (AssertStmt (IntExpr 33037) "E"))
(PrintCmd "o")
(WriteImageCmd (FloatExpr 0) "")
(WriteImageCmd (CallExpr X2w_) "")
(ShowCmd (VarExpr c))
(ShowCmd (FloatExpr 0))
(PrintCmd "")
(StmtCmd (AssertStmt (IntExpr 7) ""))
