(PrintCmd "")
(TimeCmd (ReadImageCmd "e{" (VarArgument f4L_7s.)))
(ShowCmd (CallExpr G9g.))
(ReadImageCmd "" (VarArgument F))
(ShowCmd (CallExpr j))
(WriteImageCmd (CallExpr H3U_ (IntExpr 6)) ":")
(ReadImageCmd "" (VarArgument a1N.))
(ReadImageCmd "" (VarArgument K9N_))
(WriteImageCmd (VarExpr j0i.9R.7o.) "")
(TimeCmd (ShowCmd (VarExpr d)))
