(ReadImageCmd "+" (VarArgument A))
(WriteImageCmd (VarExpr Q7D.) "")
(StmtCmd (AssertStmt (VarExpr P2v_5I_) ""))
(StmtCmd (LetStmt (ArgLValue (VarArgument P)) (IntExpr 5)))
(ReadImageCmd "#" (VarArgument d7x.))
(StmtCmd (AssertStmt (FloatExpr 9142652) "mp:"))
(ShowCmd (FloatExpr 0))
(ShowCmd (VarExpr v0H_0b_5I_))
(StmtCmd (AssertStmt (IntExpr 660) ""))
