(PrintCmd "6")
(WriteImageCmd (VarExpr d7R.) "p")
(WriteImageCmd (FloatExpr 0) "")
(ReadImageCmd "" (VarArgument u))
(PrintCmd "")
(ShowCmd (CallExpr P5e_))
(ReadImageCmd "" (VarArgument o1g_0k_))
(WriteImageCmd (FloatExpr 0) "I")
(ShowCmd (FloatExpr 0))
(ReadImageCmd "" (VarArgument T1U.1o.9Y.1f_0Z.))
