(PrintCmd "n")
(TimeCmd (TimeCmd (TimeCmd (WriteImageCmd (CallExpr j3N.) ";s"))))
(ReadImageCmd "l&" (VarArgument r0D_))
(StmtCmd
 (ReturnStmt (CallExpr D (FloatExpr 0) (CallExpr O (IntExpr 2)) (VarExpr z))))
(ShowCmd (CallExpr p))
(ReadImageCmd "iIw" (VarArgument m1x_9V_))
(ReadImageCmd "" (VarArgument X9z.2W.))
(StmtCmd (AssertStmt (IntExpr 274) "kC"))
(ReadImageCmd "" (VarArgument T))
(ReadImageCmd "" (VarArgument P1e.8d.4z.))
(StmtCmd (LetStmt (ArgLValue (VarArgument t1M_)) (VarExpr J1M.)))
(ShowCmd (FloatExpr 0))
(WriteImageCmd (CallExpr d4G.8f_5V_9p_) "A")
(StmtCmd (AssertStmt (FloatExpr 28) "f"))
(WriteImageCmd (VarExpr s0s_9I.) "")
(ReadImageCmd "K A" (VarArgument U))
(TimeCmd (WriteImageCmd (FloatExpr 0) ""))
(PrintCmd "")
(WriteImageCmd (CallExpr k0b.6K_7V.1J.) "")
