(ShowCmd (CallExpr l6w_))
(PrintCmd "5")
(ReadImageCmd "" (VarArgument w))
(ReadImageCmd "" (VarArgument E))
(TimeCmd (ReadImageCmd "" (VarArgument J)))
(ShowCmd (FloatExpr 6456))
(StmtCmd (LetStmt (ArgLValue (VarArgument Z)) (IntExpr 933020)))
(PrintCmd "")
(ShowCmd (CallExpr x3t_))
(PrintCmd "")
(StmtCmd (LetStmt (ArgLValue (VarArgument K)) (IntExpr 34)))
(ShowCmd
 (CallExpr
  i7s.7k_0h_
  (CallExpr
   c5y.5o_5x_4p_
   (CallExpr k (FloatExpr 82135506))
   (VarExpr g)
   (FloatExpr 2)
   (IntExpr 7)
   (VarExpr o6g.5h_)
   (CallExpr H)
   (FloatExpr 0)
   (FloatExpr 2)
   (CallExpr E (FloatExpr 0))
   (FloatExpr 0)
   (IntExpr 76)
   (IntExpr 57)
   (IntExpr 4)
   (IntExpr 19355)
   (IntExpr 2)
   (CallExpr h5H.)
   (CallExpr h9S.0i_ (VarExpr r7b_9i_))
   (VarExpr B))))
(PrintCmd "s")
(StmtCmd (AssertStmt (IntExpr 90101) ""))
(StmtCmd (AssertStmt (IntExpr 0) ""))
(StmtCmd (LetStmt (ArgLValue (VarArgument p3W_8F_3P.)) (IntExpr 2)))
(ReadImageCmd "" (VarArgument x))
(ReadImageCmd "" (VarArgument r3G.1j_))
