(WriteImageCmd (CallExpr c9v_ (FloatExpr 1)) "P")
(ShowCmd (VarExpr H))
(StmtCmd (LetStmt (ArgLValue (VarArgument w)) (IntExpr 901)))
(PrintCmd "")
(WriteImageCmd (FloatExpr 0) "")
(ReadImageCmd "" (VarArgument W5h.3F_))
(WriteImageCmd (FloatExpr 4) "UM")
(ShowCmd (CallExpr x6L_6K_))
(ShowCmd (IntExpr 6))
