(ReadImageCmd "" (VarArgument q))
(TimeCmd (ShowCmd (VarExpr M4u.)))
(TimeCmd (WriteImageCmd (IntExpr 5) ""))
(WriteImageCmd (VarExpr d) "")
(PrintCmd "")
(TimeCmd (WriteImageCmd (VarExpr X7L.) "kw("))
(ShowCmd (IntExpr 9))
(StmtCmd (ReturnStmt (VarExpr G7G_4A.1G_7y_4R_)))
(ReadImageCmd "1RSb" (VarArgument I8a.))
