(ReadImageCmd "!" (VarArgument w))
(WriteImageCmd (IntExpr 1) "")
(TimeCmd (StmtCmd (LetStmt (ArgLValue (VarArgument g)) (VarExpr m7T.))))
(ReadImageCmd ">u?ES" (VarArgument V9x.9U_))
(PrintCmd "")
(WriteImageCmd (FloatExpr 0) "")
(PrintCmd "F")
(ShowCmd (IntExpr 0))
(ReadImageCmd "{gzF5" (VarArgument P))
(PrintCmd "")
(WriteImageCmd (VarExpr h6S_4Y_) "")
(ReadImageCmd "G" (VarArgument H4C_))
(ShowCmd (CallExpr q4M.))
(StmtCmd (ReturnStmt (FloatExpr 560)))
(PrintCmd "p[")
(TimeCmd (ShowCmd (IntExpr 338)))
(ShowCmd (FloatExpr 503543))
