(ReadImageCmd "" (VarArgument Z))
(WriteImageCmd (CallExpr W) "'")
(TimeCmd (ShowCmd (IntExpr 7)))
(TimeCmd (WriteImageCmd (FloatExpr 0) ":Oi<"))
(ReadImageCmd "" (VarArgument T0M_))
(ReadImageCmd "" (VarArgument t5w_))
(TimeCmd (ShowCmd (IntExpr 5)))
(PrintCmd "")
(StmtCmd (ReturnStmt (CallExpr Z4A_)))
(ReadImageCmd "" (VarArgument T6u_9p.0j.))
(StmtCmd (LetStmt (ArgLValue (VarArgument O)) (IntExpr 6)))
(WriteImageCmd (FloatExpr 0) "B")
(WriteImageCmd (IntExpr 6) "")
(StmtCmd (AssertStmt (IntExpr 8) ":8RK"))
(WriteImageCmd (FloatExpr 0) "2Vr")
(PrintCmd "")
(WriteImageCmd (IntExpr 4) "{].")
