(ShowCmd (IntExpr 2))
(PrintCmd "")
(PrintCmd "")
(PrintCmd "w")
(ShowCmd (IntExpr 63))
(TimeCmd (WriteImageCmd (IntExpr 931) "Z"))
(WriteImageCmd (VarExpr z4P_) "L")
(TimeCmd (WriteImageCmd (CallExpr o (VarExpr l)) ""))
(StmtCmd (LetStmt (ArgLValue (VarArgument k)) (FloatExpr 0)))
(WriteImageCmd (FloatExpr 310) "")
(ShowCmd (IntExpr 5))
(ReadImageCmd "" (VarArgument N6f.))
(ShowCmd (VarExpr h))
(ShowCmd (CallExpr g))
(WriteImageCmd (IntExpr 2) "")
(WriteImageCmd (IntExpr 696) "")
