(PrintCmd "Y")
(WriteImageCmd (CallExpr U) "")
(ShowCmd (IntExpr 36))
(ReadImageCmd "" (VarArgument R))
(ReadImageCmd "" (VarArgument G))
(ReadImageCmd "" (VarArgument r9T_))
(ShowCmd (CallExpr e4H.))
(WriteImageCmd (FloatExpr 0) ",Sc")
(PrintCmd "`")
(WriteImageCmd (VarExpr J4t_) ";Wv4U")
(ShowCmd (IntExpr 542))
(ReadImageCmd "" (VarArgument k))
(TimeCmd (TimeCmd (ShowCmd (FloatExpr 46581746062))))
(TimeCmd (TimeCmd (ShowCmd (FloatExpr 637))))
(WriteImageCmd (IntExpr 7) "")
(PrintCmd "H")
(ReadImageCmd ")M}|" (VarArgument s6f_5P_))
(StmtCmd
 (ReturnStmt (CallExpr A3f. (CallExpr y) (CallExpr l0W_5j. (IntExpr 7161)))))
(TimeCmd (WriteImageCmd (CallExpr a (IntExpr 1)) ""))
