(ReadImageCmd "x" (VarArgument b0s_))
(StmtCmd (AssertStmt (IntExpr 970) ""))
(ShowCmd (VarExpr F0J_))
(PrintCmd "")
(ReadImageCmd "1hG!" (VarArgument c))
(ShowCmd (FloatExpr 34))
(WriteImageCmd (VarExpr r) "m&fc")
(WriteImageCmd (IntExpr 1613) "6")
(StmtCmd (LetStmt (ArgLValue (VarArgument i)) (IntExpr 37)))
(ShowCmd (CallExpr M6G_))
