(ReadImageCmd "" (VarArgument o))
(TimeCmd (ShowCmd (CallExpr v4Y_3l.)))
(PrintCmd "")
(WriteImageCmd (IntExpr 80) "0")
(ShowCmd (VarExpr G9E.))
(TimeCmd (ReadImageCmd "" (VarArgument b3f_)))
(ReadImageCmd "8$v51C" (VarArgument T))
(StmtCmd (ReturnStmt (VarExpr Z2z_)))
(StmtCmd (LetStmt (ArgLValue (VarArgument R4y.)) (IntExpr 32)))
(PrintCmd "HQo")
(WriteImageCmd (VarExpr r) "")
(WriteImageCmd (FloatExpr 6501) "")
