(StmtCmd (AssertStmt (FloatExpr 0) ""))
(StmtCmd (ReturnStmt (VarExpr e7w_)))
(StmtCmd (AssertStmt (FloatExpr 46) ""))
(ShowCmd (FloatExpr 15))
(ShowCmd (CallExpr M (IntExpr 427) (FloatExpr 0)))
(ShowCmd (IntExpr 823))
(WriteImageCmd (CallExpr m5G.) "")
(PrintCmd "")
(ShowCmd (FloatExpr 0))
(WriteImageCmd (VarExpr S8F_6j.) "H")
(StmtCmd (AssertStmt (CallExpr Z (VarExpr c3P.9P.9x.)) ""))
