(TimeCmd (ReadImageCmd "Z" (VarArgument h)))
(ReadImageCmd "" (VarArgument h0R_))
(TimeCmd (ReadImageCmd "N'>" (VarArgument R2W_0b.)))
(StmtCmd (LetStmt (ArgLValue (VarArgument F)) (FloatExpr 14281)))
(PrintCmd "K-")
(ReadImageCmd "" (VarArgument D))
(WriteImageCmd (VarExpr Q) "tg")
(TimeCmd (ReadImageCmd "" (VarArgument a)))
(ReadImageCmd "/" (VarArgument c))
(WriteImageCmd (IntExpr 4) "I")
(PrintCmd "v")
