(TimeCmd (PrintCmd "Dl-"))
(TimeCmd (ReadImageCmd "CP5Ft d" (VarArgument O8K.5m.7d.8w_2A.2e_)))
(TimeCmd (ReadImageCmd "" (VarArgument U0v_)))
(TimeCmd (PrintCmd "U="))
(ReadImageCmd "" (VarArgument c5H.))
(TimeCmd (WriteImageCmd (CallExpr U (FloatExpr 0) (VarExpr k8h.)) ";"))
(PrintCmd "")
(WriteImageCmd (VarExpr h4z_3r.2c.4s.1s.) "G")
(StmtCmd (LetStmt (ArgLValue (VarArgument L8O.9f_)) (FloatExpr 2160)))
(ShowCmd (FloatExpr 0))
(StmtCmd (AssertStmt (VarExpr P2J.) ""))
(ReadImageCmd "" (VarArgument b))
(TimeCmd (PrintCmd "K"))
(ReadImageCmd "*" (VarArgument J3w.5L.))
(TimeCmd (ShowCmd (CallExpr K)))
(PrintCmd "")
(WriteImageCmd (FloatExpr 95359) "")
(ShowCmd (IntExpr 655))
