(PrintCmd "4")
(ShowCmd (IntExpr 6))
(PrintCmd "")
(PrintCmd "")
(PrintCmd "")
(StmtCmd
 (LetStmt
  (ArgLValue (VarArgument L2A.8D.2Q_))
  (CallExpr d (CallExpr O4H. (CallExpr R (FloatExpr 741))))))
(ReadImageCmd "" (VarArgument X3T_3V.8p.9G.7P_))
(ShowCmd
 (CallExpr
  d
  (CallExpr N9i_7K_)
  (CallExpr
   z0y.
   (IntExpr 3)
   (FloatExpr 0)
   (CallExpr
    E3m.1P.
    (VarExpr e)
    (FloatExpr 75125934)
    (VarExpr z1P.)
    (CallExpr w)
    (CallExpr S (VarExpr v) (IntExpr 6) (IntExpr 0))
    (CallExpr B5T.6w_)
    (IntExpr 6)
    (CallExpr u)
    (CallExpr o (IntExpr 86))
    (FloatExpr 0)
    (FloatExpr 0)
    (CallExpr r)
    (FloatExpr 6)
    (FloatExpr 67)
    (CallExpr X2W.)
    (VarExpr c3c.0f_)
    (VarExpr Q)
    (VarExpr r)
    (CallExpr e (CallExpr h) (IntExpr 0) (IntExpr 0))
    (VarExpr R)
    (VarExpr O)
    (FloatExpr 48362)
    (IntExpr 75)
    (FloatExpr 0)
    (VarExpr N5o_8T_)
    (VarExpr c8r_2l.)
    (FloatExpr 0)
    (FloatExpr 0)
    (FloatExpr 0)
    (VarExpr Y0P.)
    (VarExpr K)
    (FloatExpr 498)
    (FloatExpr 94))
   (VarExpr D9r_7k_6V.)
   (CallExpr
    E2h_1c_4G.0t.
    (CallExpr w8H. (IntExpr 4))
    (VarExpr W8P.4i.4d.7D_2K.9K_5D_0P_)
    (CallExpr r2C. (VarExpr x))
    (CallExpr Z)
    (IntExpr 5)
    (CallExpr t3G_1g. (FloatExpr 0))
    (FloatExpr 5)
    (FloatExpr 0)
    (VarExpr C)
    (VarExpr F9k.)
    (VarExpr z)
    (VarExpr l4t_7u.)
    (VarExpr J9U_4z.)
    (CallExpr C)
    (FloatExpr 0)
    (VarExpr U)
    (IntExpr 30)
    (VarExpr I6J_7h_3f.)
    (IntExpr 41)
    (FloatExpr 0)
    (VarExpr E)
    (IntExpr 31761)
    (FloatExpr 502)
    (FloatExpr 0)
    (VarExpr r)
    (VarExpr H9x_6i.5l.2l.7b.)
    (IntExpr 63)
    (IntExpr 479)
    (VarExpr R)
    (FloatExpr 32)
    (CallExpr o7A_6t_3y_9Z.4X_3S.3F_)
    (IntExpr 668)
    (FloatExpr 0)
    (VarExpr V)
    (FloatExpr 0)
    (VarExpr w)
    (CallExpr
     y4o_2a.0Y_1c_
     (CallExpr p5o. (CallExpr k7k.5T.0T_3P_))
     (CallExpr
      B3o.8k_
      (VarExpr S7J.8Q_)
      (CallExpr C)
      (CallExpr e4P.)
      (VarExpr c0u.)))
    (FloatExpr 0))
   (FloatExpr 4)
   (FloatExpr 0)
   (VarExpr l)
   (IntExpr 9990578)
   (VarExpr x)
   (CallExpr
    h
    (FloatExpr 315)
    (FloatExpr 54)
    (VarExpr B)
    (FloatExpr 626853492)
    (FloatExpr 0)
    (IntExpr 63))
   (VarExpr V0z.)
   (CallExpr d)
   (CallExpr
    p
    (CallExpr J (VarExpr f))
    (IntExpr 1)
    (CallExpr M (CallExpr y (CallExpr B0B. (IntExpr 8) (FloatExpr 68))))
    (IntExpr 1)
    (IntExpr 704)
    (FloatExpr 0)
    (FloatExpr 0)
    (VarExpr z))
   (IntExpr 305)
   (CallExpr r)
   (IntExpr 9)
   (FloatExpr 0))
  (IntExpr 618)
  (VarExpr e9g_)
  (IntExpr 853)
  (CallExpr o)
  (FloatExpr 0)
  (FloatExpr 0)
  (CallExpr O8P_)
  (IntExpr 5)
  (FloatExpr 0)
  (FloatExpr 0)
  (FloatExpr 0)
  (IntExpr 6)
  (CallExpr Z6A.)))
(TimeCmd (PrintCmd ""))
(ReadImageCmd "" (VarArgument O))
(PrintCmd "")
