(StmtCmd (AssertStmt (VarExpr d1p_) ""))
(ShowCmd (IntExpr 73))
(WriteImageCmd (IntExpr 7) "")
(StmtCmd (LetStmt (ArgLValue (VarArgument s)) (CallExpr U (VarExpr D7d_))))
(StmtCmd (LetStmt (ArgLValue (VarArgument t)) (IntExpr 47)))
(PrintCmd "'M")
(ShowCmd (CallExpr X (IntExpr 0)))
(ShowCmd (VarExpr b0g_))
(ShowCmd (VarExpr L9s.))
