(ReadImageCmd "" (VarArgument Y))
(PrintCmd "")
(StmtCmd (LetStmt (ArgLValue (VarArgument M)) (IntExpr 3783)))
(ShowCmd (FloatExpr 0))
(ShowCmd (IntExpr 850932871))
(ReadImageCmd "" (VarArgument F))
(PrintCmd "s")
(ShowCmd (FloatExpr 0))
(StmtCmd (AssertStmt (VarExpr m6J.) ""))
