(StmtCmd (LetStmt (ArgLValue (VarArgument E2f.3y.)) (CallExpr l2V.1l_)))
(TimeCmd (ShowCmd (IntExpr 253)))
(TimeCmd (ShowCmd (VarExpr t)))
(StmtCmd (LetStmt (ArgLValue (VarArgument H)) (IntExpr 896)))
(ShowCmd (IntExpr 1))
(PrintCmd "")
(StmtCmd (AssertStmt (VarExpr e) "?"))
(WriteImageCmd (IntExpr 41) "")
(WriteImageCmd
 (CallExpr
  O
  (VarExpr F5Y_9Q.9P.3r_)
  (FloatExpr 30590)
  (CallExpr I)
  (CallExpr E)
  (IntExpr 534)
  (FloatExpr 0)
  (CallExpr Z3x_3W. (VarExpr o1m.2G.8K_9n.0N.))
  (FloatExpr 227))
 "")
(ReadImageCmd "" (VarArgument l7d.7C.))
(TimeCmd (ShowCmd (IntExpr 0)))
(PrintCmd "$t+K")
(WriteImageCmd (CallExpr G) "")
