(StmtCmd (ReturnStmt (IntExpr 5)))
(PrintCmd "")
(WriteImageCmd (VarExpr O2Y.4S_5Q_) "")
(WriteImageCmd (FloatExpr 0) "L")
(ReadImageCmd "lhJ" (VarArgument c5Y.))
(TimeCmd (ShowCmd (IntExpr 389)))
(TimeCmd (WriteImageCmd (CallExpr h (VarExpr Q6G_0E.)) "HFk"))
(WriteImageCmd (VarExpr z) "")
(StmtCmd (ReturnStmt (VarExpr N)))
(ReadImageCmd "" (VarArgument f))
(WriteImageCmd (FloatExpr 4) "3DOB")
(StmtCmd (ReturnStmt (VarExpr N5b_)))
(ReadImageCmd "=V}" (VarArgument T4D.2e.3r_4n.5E.5p_8i.))
(TimeCmd (WriteImageCmd (FloatExpr 0) ""))
(ReadImageCmd "B" (VarArgument m))
(PrintCmd "")
(WriteImageCmd (VarExpr I5O.7y_) "D")
(ReadImageCmd "F" (VarArgument j8z_))
