(TimeCmd (StmtCmd (ReturnStmt (CallExpr h))))
(StmtCmd (ReturnStmt (VarExpr H0i.5R.5I_)))
(PrintCmd "")
(StmtCmd (ReturnStmt (CallExpr y (FloatExpr 0))))
(PrintCmd "O")
(ReadImageCmd "h=t" (VarArgument T))
(TimeCmd (StmtCmd (ReturnStmt (CallExpr g8v. (CallExpr p3m_4i.)))))
(ShowCmd (IntExpr 9))
(StmtCmd (LetStmt (ArgLValue (VarArgument E1g_)) (IntExpr 92)))
