(PrintCmd "&")
(PrintCmd "X")
(ReadImageCmd "UF" (VarArgument T))
(ReadImageCmd "E" (VarArgument S3o_))
(ReadImageCmd "zMnd" (VarArgument o))
(PrintCmd "")
(PrintCmd "R")
(ShowCmd (FloatExpr 0))
(PrintCmd "")
(ShowCmd (VarExpr O1y.8w_2t_6J.))
(ShowCmd (CallExpr t7L.1p.6a.))
