(ShowCmd (CallExpr x6y.8a.))
(TimeCmd (ReadImageCmd ";" (VarArgument V)))
(WriteImageCmd (VarExpr A) "")
(TimeCmd (WriteImageCmd (VarExpr K8S.) ""))
(PrintCmd "9")
(StmtCmd (AssertStmt (FloatExpr 27) ""))
(PrintCmd "")
(ShowCmd (VarExpr H5J.2L.2Q.3Y_6D.3t.))
(StmtCmd (AssertStmt (IntExpr 3) "'"))
(WriteImageCmd (VarExpr h7I.6j.6b_) "M")
(WriteImageCmd (FloatExpr 0) "3")
(PrintCmd "")
(StmtCmd (ReturnStmt (VarExpr s0N.)))
(WriteImageCmd (FloatExpr 0) "")
(ReadImageCmd "h" (VarArgument s4M_))
(TimeCmd (TimeCmd (ReadImageCmd "" (VarArgument g6k_5D_3x.))))
(WriteImageCmd (VarExpr u) "")
(ReadImageCmd "" (VarArgument k7f.1C.0Z.))
(WriteImageCmd (IntExpr 0) "")
