(PrintCmd "yV")
(ShowCmd (IntExpr 0))
(ReadImageCmd "" (VarArgument W))
(ShowCmd (FloatExpr 0))
(TimeCmd (ShowCmd (IntExpr 4)))
(PrintCmd "")
(TimeCmd (WriteImageCmd (FloatExpr 9) ""))
(WriteImageCmd (IntExpr 614) "Sdc")
(PrintCmd "")
(StmtCmd (AssertStmt (VarExpr F) "J!"))
(ReadImageCmd "B" (VarArgument Y))
(StmtCmd
 (AssertStmt
  (CallExpr
   m3t_1A_
   (IntExpr 0)
   (CallExpr C1g.2h.3r_4y. (VarExpr o3X.) (CallExpr S)))
  "CC"))
(PrintCmd "0")
(WriteImageCmd (FloatExpr 369715305) "")
(PrintCmd "")
(TimeCmd (StmtCmd (LetStmt (ArgLValue (VarArgument q)) (FloatExpr 913880))))
(WriteImageCmd (IntExpr 46) "")
(StmtCmd (ReturnStmt (FloatExpr 0)))
(ReadImageCmd "" (VarArgument g))
