(PrintCmd "")
(StmtCmd (LetStmt (ArgLValue (VarArgument K8u_4P_1t_4A.6r.3x_)) (CallExpr o)))
(PrintCmd "")
(WriteImageCmd (VarExpr P7w_8r.) "")
(WriteImageCmd (FloatExpr 569006964487) "")
(ReadImageCmd "~" (VarArgument K))
(StmtCmd (LetStmt (ArgLValue (VarArgument d)) (VarExpr w)))
(StmtCmd (AssertStmt (IntExpr 9287) ""))
(ShowCmd (CallExpr j9O_4f.))
(PrintCmd "")
(TimeCmd
 (StmtCmd (LetStmt (ArgLValue (VarArgument H3D_)) (VarExpr f3p.6N.7a_))))
(WriteImageCmd (IntExpr 447182) "")
(ShowCmd (FloatExpr 264))
(PrintCmd "%F")
(ReadImageCmd "{" (VarArgument u))
(WriteImageCmd (IntExpr 7) "")
