(WriteImageCmd (FloatExpr 0) "Yg")
(WriteImageCmd (FloatExpr 0) "_T")
(StmtCmd (AssertStmt (FloatExpr 0) ""))
(StmtCmd (LetStmt (ArgLValue (VarArgument z)) (IntExpr 5)))
(ReadImageCmd "" (VarArgument u))
(WriteImageCmd (IntExpr 9632) "")
(StmtCmd (ReturnStmt (IntExpr 635274)))
(ShowCmd (CallExpr Z1e_))
(PrintCmd "S")
(ReadImageCmd "rNc" (VarArgument m3B_3C.))
(ShowCmd (FloatExpr 2))
