(PrintCmd "")
(PrintCmd "")
(PrintCmd "Ph")
(ShowCmd (CallExpr k))
(PrintCmd "")
(ReadImageCmd "<A" (VarArgument Z))
(StmtCmd (ReturnStmt (CallExpr b4q_ (VarExpr m))))
(ShowCmd (IntExpr 44))
(StmtCmd (ReturnStmt (CallExpr S3n_)))
(ReadImageCmd "dU:" (VarArgument y2R_))
(PrintCmd "rN")
(StmtCmd (ReturnStmt (FloatExpr 0)))
(WriteImageCmd (IntExpr 9653) "J")
(WriteImageCmd (FloatExpr 0) "9zM")
(ShowCmd (CallExpr i))
(ShowCmd (IntExpr 90911))
(WriteImageCmd (VarExpr m) "n")
