(TimeCmd (WriteImageCmd (VarExpr A) "Igz"))
(ReadImageCmd "" (VarArgument p))
(ReadImageCmd "" (VarArgument l))
(WriteImageCmd (VarExpr h1H_) "")
(ReadImageCmd "" (VarArgument m4a_))
(ReadImageCmd "" (VarArgument P))
