(PrintCmd "]lG#")
(PrintCmd "")
(TimeCmd (ShowCmd (FloatExpr 0)))
(StmtCmd (LetStmt (ArgLValue (VarArgument E)) (VarExpr t)))
(WriteImageCmd (IntExpr 1) "")
(ReadImageCmd "" (VarArgument r9A_3y_))
(ShowCmd (FloatExpr 0))
(ReadImageCmd "V" (VarArgument e))
(WriteImageCmd (FloatExpr 0) "Zp")
(WriteImageCmd (VarExpr b) "")
(ShowCmd (VarExpr Q3E.0W.1e_))
