(ReadImageCmd "" (VarArgument v9H.))
(PrintCmd "~L:")
(StmtCmd (AssertStmt (CallExpr F (VarExpr U) (VarExpr q5f.)) ""))
(ShowCmd (CallExpr s))
(PrintCmd "Gv")
(WriteImageCmd (FloatExpr 8) "")
(TimeCmd (WriteImageCmd (CallExpr M) " "))
(ShowCmd (CallExpr n))
(ShowCmd (FloatExpr 438007823))
(ReadImageCmd "" (VarArgument f0r_))
(WriteImageCmd (VarExpr E8z_0J.) "")
(TimeCmd (PrintCmd "!"))
(TimeCmd (TimeCmd (WriteImageCmd (VarExpr j4y.) "")))
(PrintCmd "}Y")
