(TimeCmd (ReadImageCmd "" (VarArgument f1k.)))
(ReadImageCmd "Z" (VarArgument X6X.))
(TimeCmd (TimeCmd (TimeCmd (TimeCmd (PrintCmd "")))))
(StmtCmd (AssertStmt (FloatExpr 0) "Z"))
(ShowCmd (IntExpr 1))
(ShowCmd (FloatExpr 8844))
(WriteImageCmd (CallExpr F8I_1z_) "i")
(ReadImageCmd "k" (VarArgument w9i.))
(TimeCmd (TimeCmd (PrintCmd "n1")))
(PrintCmd "")
(PrintCmd "")
(ShowCmd (FloatExpr 0))
(PrintCmd "w5")
(PrintCmd "")
(StmtCmd (ReturnStmt (CallExpr Y (IntExpr 3))))
(StmtCmd (LetStmt (ArgLValue (VarArgument b4n_1Y.4b_)) (IntExpr 2)))
(ShowCmd (VarExpr h7w_8Q_))
(TimeCmd (ReadImageCmd "Ux" (VarArgument e)))
(StmtCmd (LetStmt (ArgLValue (VarArgument H)) (VarExpr o)))
