(PrintCmd ".")
(ReadImageCmd "7b" (VarArgument w))
(StmtCmd (AssertStmt (FloatExpr 0) "{9:/"))
(ShowCmd (VarExpr F5m.))
(WriteImageCmd (CallExpr p5S_1x_) "{Z")
(PrintCmd "")
(StmtCmd (AssertStmt (FloatExpr 7) "R<"))
(PrintCmd "")
(ReadImageCmd "" (VarArgument y))
(StmtCmd (AssertStmt (VarExpr S) ""))
(WriteImageCmd (VarExpr x) "")
(ReadImageCmd "" (VarArgument M0T.6g_))
(ShowCmd (VarExpr U))
(PrintCmd "t")
(ReadImageCmd "" (VarArgument a1g.9D_))
