(ShowCmd (IntExpr 2))
(ShowCmd (VarExpr c))
(WriteImageCmd (CallExpr L9G. (VarExpr N)) "")
(WriteImageCmd (IntExpr 8128) "")
(ReadImageCmd "" (VarArgument c))
(WriteImageCmd (FloatExpr 6) "")
(ReadImageCmd "" (VarArgument o7L.))
(ShowCmd (FloatExpr 36733230682))
(ReadImageCmd "U" (VarArgument A8a_))
(WriteImageCmd (VarExpr b) "aq")
(PrintCmd "")
(ShowCmd (IntExpr 6149))
(PrintCmd "")
(ShowCmd (IntExpr 9))
(PrintCmd "<![C,/s+k")
(StmtCmd (LetStmt (ArgLValue (VarArgument T0G.)) (FloatExpr 8697714)))
