(TimeCmd (StmtCmd (AssertStmt (CallExpr V) "0")))
(PrintCmd "")
(ReadImageCmd "" (VarArgument P))
(StmtCmd (LetStmt (ArgLValue (VarArgument O)) (IntExpr 5450)))
(ReadImageCmd "AD~" (VarArgument c))
(ShowCmd (IntExpr 6))
(ReadImageCmd "" (VarArgument R6y.))
(TimeCmd (ReadImageCmd "Y" (VarArgument d0S_2l.)))
(TimeCmd (WriteImageCmd (FloatExpr 0) "6vn"))
(ReadImageCmd "v" (VarArgument N8O_1k_4B.9T_))
(PrintCmd "")
(TimeCmd (ReadImageCmd "" (VarArgument D)))
(ShowCmd (FloatExpr 0))
(TimeCmd (ReadImageCmd "" (VarArgument s)))
