(ShowCmd (VarExpr d))
(ReadImageCmd ";]#p_" (VarArgument g))
(PrintCmd "")
(WriteImageCmd (CallExpr Z) "")
(ReadImageCmd "" (VarArgument m4Y_))
(TimeCmd (PrintCmd ""))
(TimeCmd (WriteImageCmd (FloatExpr 1) ""))
(ReadImageCmd "" (VarArgument W1v.4B_))
(ShowCmd (VarExpr b8s_1c.6A.))
(ReadImageCmd "=y@>" (VarArgument R5R.0M.))
(StmtCmd (LetStmt (ArgLValue (VarArgument E)) (CallExpr l9d_2R_8k.)))
(PrintCmd "D")
(PrintCmd "")
(ShowCmd (CallExpr b))
