(TimeCmd (TimeCmd (WriteImageCmd (FloatExpr 5) "{")))
(WriteImageCmd (FloatExpr 3138621) "")
(StmtCmd (AssertStmt (CallExpr Z6t. (IntExpr 3)) ""))
(TimeCmd (PrintCmd ""))
(TimeCmd (TimeCmd (PrintCmd "8zCe")))
(TimeCmd (ShowCmd (CallExpr e (IntExpr 22))))
(ShowCmd (FloatExpr 39162))
(StmtCmd (ReturnStmt (IntExpr 8)))
