(WriteImageCmd (IntExpr 65) "")
(TimeCmd (TimeCmd (TimeCmd (PrintCmd ""))))
(StmtCmd (LetStmt (ArgLValue (VarArgument S)) (VarExpr l)))
(StmtCmd (LetStmt (ArgLValue (VarArgument x1h.)) (FloatExpr 789)))
(ReadImageCmd "" (VarArgument N))
(ReadImageCmd "3" (VarArgument V6E_9l_))
(PrintCmd "sK")
(TimeCmd (StmtCmd (LetStmt (ArgLValue (VarArgument l)) (FloatExpr 0))))
(ShowCmd (FloatExpr 0))
(TimeCmd (ShowCmd (IntExpr 4)))
