(TimeCmd (ShowCmd (FloatExpr 0)))
(ReadImageCmd "vE" (VarArgument V))
(WriteImageCmd (VarExpr L) "m")
(StmtCmd (ReturnStmt (IntExpr 39269)))
(TimeCmd (TimeCmd (ShowCmd (IntExpr 3))))
(PrintCmd "|")
(WriteImageCmd (FloatExpr 0) "jM")
(TimeCmd (TimeCmd (WriteImageCmd (FloatExpr 2659929) "")))
(WriteImageCmd (VarExpr d) "Q")
(ReadImageCmd "" (VarArgument b))
(TimeCmd (ShowCmd (IntExpr 7649)))
(ShowCmd (CallExpr g2A.2X.))
(WriteImageCmd (IntExpr 1) "j4+gp")
(StmtCmd (ReturnStmt (IntExpr 5)))
(PrintCmd "")
(ShowCmd (IntExpr 2846))
