(StmtCmd (AssertStmt (FloatExpr 0) "~"))
(ShowCmd (CallExpr g))
(PrintCmd "*,")
(StmtCmd (AssertStmt (IntExpr 38) "m"))
(ShowCmd (FloatExpr 0))
(ShowCmd
 (CallExpr
  q
  (IntExpr 228)
  (IntExpr 9)
  (IntExpr 96)
  (IntExpr 2085249)
  (CallExpr l (IntExpr 1))))
(StmtCmd (AssertStmt (VarExpr q) "D"))
(ReadImageCmd "" (VarArgument H))
(PrintCmd "")
(StmtCmd (LetStmt (ArgLValue (VarArgument W)) (FloatExpr 0)))
(StmtCmd
 (ReturnStmt
  (CallExpr
   m1B_8D_
   (VarExpr J7o_7Y.2y_)
   (FloatExpr 0)
   (VarExpr L8b.)
   (IntExpr 1)
   (FloatExpr 0)
   (CallExpr C (VarExpr w0R.))
   (IntExpr 18454)
   (FloatExpr 0)
   (VarExpr f)
   (IntExpr 4)
   (CallExpr L)
   (VarExpr c)
   (CallExpr o2T.2T_ (FloatExpr 0))
   (VarExpr O)
   (IntExpr 8)
   (FloatExpr 0)
   (IntExpr 25)
   (IntExpr 31)
   (VarExpr n7p_8k.5z.)
   (VarExpr H)
   (VarExpr Z0L_)
   (VarExpr k5o.7R_)
   (IntExpr 988)
   (VarExpr C)
   (CallExpr B6P.)
   (VarExpr q4p_)
   (FloatExpr 0)
   (FloatExpr 2)
   (CallExpr K3i_ (VarExpr c))
   (CallExpr o)
   (FloatExpr 0))))
(WriteImageCmd (CallExpr W3Q_2c.) "")
(ReadImageCmd "" (VarArgument E7Q.7I_7B.2e_))
