(ShowCmd (IntExpr 8))
(ShowCmd (VarExpr s0E_))
(ShowCmd (IntExpr 5016))
(PrintCmd "")
(ReadImageCmd "8'k" (VarArgument Q3A_))
(ReadImageCmd "" (VarArgument C8E_))
(TimeCmd (TimeCmd (ReadImageCmd "" (VarArgument K7H.9r_5U.0j_))))
(ReadImageCmd "" (VarArgument b9H.))
(TimeCmd (WriteImageCmd (CallExpr I) "*_*"))
(PrintCmd "")
(TimeCmd (ReadImageCmd "" (VarArgument k)))
(PrintCmd "+f^")
(PrintCmd "")
(TimeCmd (WriteImageCmd (VarExpr A) ")CM?R/"))
(ReadImageCmd "HX" (VarArgument f7a.0Q.7h.))
(StmtCmd (LetStmt (ArgLValue (VarArgument E)) (FloatExpr 0)))
(StmtCmd (AssertStmt (FloatExpr 0) ""))
(ReadImageCmd "" (VarArgument t))
