(WriteImageCmd (IntExpr 4) "G")
(TimeCmd (StmtCmd (ReturnStmt (FloatExpr 2667390382925111))))
(TimeCmd (ReadImageCmd "" (VarArgument O8H.7j.)))
(ReadImageCmd "i" (VarArgument K))
(StmtCmd (ReturnStmt (IntExpr 2)))
(PrintCmd "")
(PrintCmd "")
(StmtCmd (ReturnStmt (VarExpr a7P_3n_7w.)))
(PrintCmd "")
(PrintCmd "")
(WriteImageCmd (CallExpr q (VarExpr G)) " ")
(TimeCmd (TimeCmd (ShowCmd (IntExpr 36))))
(TimeCmd (TimeCmd (ReadImageCmd "" (VarArgument u))))
(ReadImageCmd "R" (VarArgument u3a.0I_))
(WriteImageCmd (IntExpr 18) "n")
(ReadImageCmd "F#" (VarArgument r))
(ShowCmd (IntExpr 3))
(PrintCmd "")
