(WriteImageCmd (CallExpr j1e. (IntExpr 3)) "")
(ShowCmd (VarExpr O))
(StmtCmd (ReturnStmt (CallExpr A7b.1t. (VarExpr e2F.))))
(PrintCmd "9")
(WriteImageCmd (CallExpr B) "")
(WriteImageCmd (IntExpr 0) "")
(StmtCmd (ReturnStmt (FloatExpr 382)))
(ReadImageCmd "6" (VarArgument L))
(ShowCmd (CallExpr A (FloatExpr 0) (CallExpr q5d_) (CallExpr B)))
(WriteImageCmd (FloatExpr 0) "")
(ShowCmd (FloatExpr 13))
(ShowCmd (CallExpr z))
(WriteImageCmd (VarExpr W4C_) "r")
(ShowCmd (VarExpr D))
(WriteImageCmd (IntExpr 6556) "")
(StmtCmd (LetStmt (ArgLValue (VarArgument i)) (FloatExpr 874616735)))
(StmtCmd (AssertStmt (IntExpr 3) "~N*"))
(ReadImageCmd "," (VarArgument f))
