(ReadImageCmd "Gr7" (VarArgument l))
(WriteImageCmd (VarExpr o9e.) "")
(WriteImageCmd (VarExpr j) "")
(PrintCmd "j")
(StmtCmd (AssertStmt (IntExpr 671) ""))
(ShowCmd (VarExpr D2A_7x.))
(StmtCmd (LetStmt (ArgLValue (VarArgument i3z_9C_6L.)) (IntExpr 5958)))
(PrintCmd "")
(ShowCmd (FloatExpr 466))
(ReadImageCmd "Q_" (VarArgument m))
(ShowCmd (FloatExpr 960))
