(ShowCmd (IntExpr 1))
(WriteImageCmd (VarExpr L) "!/Mc>")
(PrintCmd "_")
(PrintCmd "")
(ShowCmd (CallExpr g (IntExpr 1)))
(WriteImageCmd
 (CallExpr n1f_2I_ (VarExpr e8u_) (FloatExpr 0) (VarExpr M2l_) (IntExpr 54))
 "")
(TimeCmd (TimeCmd (PrintCmd "")))
(TimeCmd (StmtCmd (LetStmt (ArgLValue (VarArgument W9T.)) (IntExpr 97))))
(ReadImageCmd "" (VarArgument s3K_))
(WriteImageCmd (IntExpr 702) "")
(WriteImageCmd (CallExpr W (IntExpr 21)) "w5z2_")
