(TimeCmd (ShowCmd (VarExpr v)))
(WriteImageCmd
 (CallExpr
  b4h_0W.
  (IntExpr 826834)
  (CallExpr c5t_5A.)
  (FloatExpr 0)
  (IntExpr 7)
  (IntExpr 26)
  (VarExpr m0G.1f_3O_)
  (CallExpr f (VarExpr I))
  (VarExpr l)
  (IntExpr 42)
  (FloatExpr 0)
  (CallExpr U)
  (CallExpr L)
  (IntExpr 230)
  (IntExpr 8)
  (VarExpr o)
  (FloatExpr 0)
  (CallExpr Z5W.0y.7w_2A_)
  (FloatExpr 3)
  (CallExpr
   c
   (VarExpr p)
   (CallExpr i5v.2z_)
   (VarExpr x)
   (FloatExpr 532285)
   (FloatExpr 0)
   (IntExpr 5287)
   (IntExpr 2369)
   (VarExpr e))
  (VarExpr z)
  (IntExpr 338)
  (IntExpr 2)
  (IntExpr 50)
  (CallExpr F)
  (IntExpr 2)
  (VarExpr C)
  (FloatExpr 0)
  (FloatExpr 0)
  (IntExpr 40)
  (CallExpr w8c.2K_3J.8l.8k.7K.3F.3l_ (IntExpr 4))
  (VarExpr O7d_2f.)
  (IntExpr 9)
  (FloatExpr 0)
  (FloatExpr 0)
  (FloatExpr 0)
  (FloatExpr 0)
  (IntExpr 6))
 "L")
(StmtCmd
 (LetStmt (ArgLValue (VarArgument i8m_)) (CallExpr a8t.4v_ (IntExpr 78983))))
(TimeCmd (ShowCmd (FloatExpr 0)))
(ReadImageCmd "" (VarArgument N))
(PrintCmd "=K")
(TimeCmd (WriteImageCmd (FloatExpr 0) ""))
(WriteImageCmd (FloatExpr 0) "]6 ")
(PrintCmd "A")
