(ShowCmd (FloatExpr 0))
(ReadImageCmd "y" (VarArgument S3Y.))
(ShowCmd (FloatExpr 72597))
(WriteImageCmd (IntExpr 2486) "")
(StmtCmd (AssertStmt (VarExpr q) ""))
(WriteImageCmd (VarExpr w) "")
(TimeCmd (WriteImageCmd (CallExpr g8J.2u.6q_ (VarExpr M)) ""))
(TimeCmd (ShowCmd (IntExpr 912)))
(PrintCmd "BJ")
(StmtCmd (AssertStmt (VarExpr h) "@tg"))
(StmtCmd (AssertStmt (VarExpr m1g.2Y.6y.) ""))
(TimeCmd (WriteImageCmd (FloatExpr 273) ""))
(TimeCmd (ShowCmd (IntExpr 1)))
(TimeCmd (PrintCmd ""))
(ShowCmd (IntExpr 735))
(StmtCmd (ReturnStmt (VarExpr j)))
