(ShowCmd (IntExpr 11))
(TimeCmd (WriteImageCmd (CallExpr a5c.5Q_6r_4A.9k_4H.9k.) "_KRotl"))
(PrintCmd "y")
(ReadImageCmd "o" (VarArgument w))
(ShowCmd (FloatExpr 0))
(StmtCmd (LetStmt (ArgLValue (VarArgument K3Q.)) (IntExpr 160333396)))
(TimeCmd (PrintCmd ""))
(ReadImageCmd " " (VarArgument u))
(ReadImageCmd "" (VarArgument S0J_))
(ShowCmd (FloatExpr 7))
(WriteImageCmd (VarExpr K) "A")
(ShowCmd (FloatExpr 0))
(ReadImageCmd "" (VarArgument E))
(WriteImageCmd (IntExpr 82) "S")
(StmtCmd (AssertStmt (FloatExpr 0) "#"))
