(StmtCmd (ReturnStmt (CallExpr d (VarExpr Z9j.5p.2y_))))
(ShowCmd (CallExpr C4p_6W.))
(TimeCmd (ShowCmd (CallExpr C8t. (IntExpr 14))))
(StmtCmd (LetStmt (ArgLValue (VarArgument S)) (VarExpr x2v.)))
(WriteImageCmd (IntExpr 2264) "[")
(WriteImageCmd (CallExpr h1E.5o_8G.2H. (VarExpr n5r_8d_6k.)) "bo")
(StmtCmd (AssertStmt (IntExpr 34) ""))
(PrintCmd "M2")
(StmtCmd (LetStmt (ArgLValue (VarArgument Z9U_9D_)) (IntExpr 1937)))
(ReadImageCmd "" (VarArgument N))
(StmtCmd
 (LetStmt (ArgLValue (VarArgument j1L.3U_1Y_3y.9P.)) (FloatExpr 61638)))
(StmtCmd (AssertStmt (IntExpr 1) "!n^"))
(ShowCmd (CallExpr S))
(PrintCmd "")
