(StmtCmd (LetStmt (ArgLValue (VarArgument P9R.1W_8D_6s.)) (VarExpr U)))
(PrintCmd "")
(PrintCmd "^")
(StmtCmd
 (LetStmt
  (ArgLValue (VarArgument t))
  (CallExpr
   J
   (VarExpr Q9S.)
   (VarExpr R)
   (FloatExpr 0)
   (CallExpr A)
   (FloatExpr 408938010)
   (IntExpr 28)
   (FloatExpr 0)
   (VarExpr a)
   (IntExpr 97)
   (FloatExpr 1)
   (CallExpr N6w.4B_7q.)
   (VarExpr b5j.4M.2q_8v_)
   (FloatExpr 0))))
(ReadImageCmd "C" (VarArgument p))
(ReadImageCmd "" (VarArgument c))
(WriteImageCmd (FloatExpr 0) "=;ex~")
(PrintCmd "")
(ShowCmd (VarExpr b8t_))
(PrintCmd "p")
(ShowCmd (VarExpr G8c.))
(ShowCmd (VarExpr X))
(ReadImageCmd "" (VarArgument r))
(PrintCmd "ez")
(ShowCmd (VarExpr M))
(WriteImageCmd (FloatExpr 966643) "n")
(PrintCmd "")
