(TimeCmd (StmtCmd (AssertStmt (IntExpr 63) "")))
(ReadImageCmd "" (VarArgument K))
(ShowCmd (FloatExpr 74))
(PrintCmd "")
(PrintCmd "")
(WriteImageCmd (IntExpr 4) "")
(ShowCmd (IntExpr 6))
(ReadImageCmd "h8Sw" (VarArgument B2z.))
(StmtCmd (LetStmt (ArgLValue (VarArgument e)) (IntExpr 5)))
(WriteImageCmd (FloatExpr 0) "i")
(WriteImageCmd (IntExpr 2) "")
(ReadImageCmd "." (VarArgument L5N.))
(WriteImageCmd (CallExpr s) "?xUj")
(ShowCmd (VarExpr m7P.0n_9i_))
(ReadImageCmd "" (VarArgument H))
