(TimeCmd (PrintCmd ""))
(StmtCmd (ReturnStmt (VarExpr w)))
(ReadImageCmd "tz" (VarArgument T))
(PrintCmd "")
(ReadImageCmd "[" (VarArgument C8T.4m.))
(StmtCmd (AssertStmt (VarExpr h) "5"))
(ReadImageCmd "" (VarArgument D))
(ReadImageCmd "" (VarArgument Y))
(PrintCmd "G")
(WriteImageCmd (FloatExpr 96) "")
(ReadImageCmd "O" (VarArgument l6R_9u.))
(ReadImageCmd "" (VarArgument X3z_))
