(StmtCmd (AssertStmt (CallExpr x0Y.) "6"))
(StmtCmd (ReturnStmt (FloatExpr 0)))
(WriteImageCmd (VarExpr h) "")
(ShowCmd (FloatExpr 1))
(WriteImageCmd (CallExpr x) "")
(PrintCmd "j")
(ShowCmd (VarExpr s7o_1C_7k.))
(StmtCmd (ReturnStmt (IntExpr 87)))
(StmtCmd (LetStmt (ArgLValue (VarArgument c)) (VarExpr r)))
