(PrintCmd "wUm")
(WriteImageCmd (IntExpr 9) "")
(ShowCmd (IntExpr 3))
(PrintCmd "")
(PrintCmd "N")
(WriteImageCmd (FloatExpr 8212194755148) "~<}")
(ReadImageCmd "" (VarArgument R6F_))
(ShowCmd (VarExpr O))
(ShowCmd (CallExpr L1a_2A.3m_1d_7a.))
(PrintCmd "")
(WriteImageCmd (CallExpr a2g_) "0")
(WriteImageCmd (VarExpr W1w.8r.9O_) "")
(StmtCmd (ReturnStmt (VarExpr O)))
(ReadImageCmd "" (VarArgument X))
(ReadImageCmd "Ha" (VarArgument m0L_6F.8g.))
(WriteImageCmd (VarExpr z) "D")
(ShowCmd (CallExpr i4z_))
