(ShowCmd (VarExpr h0P.2s_4D.1o.))
(PrintCmd "U")
(WriteImageCmd (VarExpr c) "")
(WriteImageCmd (CallExpr Q6I. (FloatExpr 0) (IntExpr 8576864)) "")
(ReadImageCmd "Y|" (VarArgument X0T.))
(ReadImageCmd "" (VarArgument H0x.7e.))
(ReadImageCmd "" (VarArgument J))
(StmtCmd (ReturnStmt (VarExpr a)))
(ReadImageCmd "" (VarArgument y))
(StmtCmd (ReturnStmt (CallExpr c1z_6S_)))
(TimeCmd (WriteImageCmd (VarExpr I) "F_"))
(TimeCmd (PrintCmd "f"))
(TimeCmd (TimeCmd (ReadImageCmd "=" (VarArgument J8z_6p.))))
(ReadImageCmd "" (VarArgument D))
