(TimeCmd (StmtCmd (LetStmt (ArgLValue (VarArgument z)) (IntExpr 6))))
(ShowCmd (IntExpr 2))
(WriteImageCmd (FloatExpr 38) "")
(ShowCmd (FloatExpr 0))
(StmtCmd (AssertStmt (FloatExpr 0) "!P"))
(WriteImageCmd (IntExpr 5) "v")
(TimeCmd (PrintCmd ""))
(PrintCmd "")
(PrintCmd "")
(WriteImageCmd (IntExpr 4) "")
(StmtCmd
 (ReturnStmt (CallExpr v9s. (IntExpr 7) (VarExpr w4d.9J.) (IntExpr 104))))
(ReadImageCmd "J]@$" (VarArgument o))
(PrintCmd "")
(StmtCmd (LetStmt (ArgLValue (VarArgument a)) (IntExpr 2)))
(ShowCmd (VarExpr N))
(PrintCmd "")
(ShowCmd (FloatExpr 614825385))
