(ShowCmd (FloatExpr 0))
(PrintCmd "3")
(ShowCmd (IntExpr 3))
(ReadImageCmd "KV" (VarArgument D))
(StmtCmd (ReturnStmt (IntExpr 66)))
(ShowCmd (VarExpr b8N_1G_))
(ReadImageCmd "" (VarArgument m2r.3v_6K.2d_))
(PrintCmd "#|s#")
(StmtCmd (AssertStmt (CallExpr E (VarExpr T)) ""))
(PrintCmd "")
(TimeCmd (PrintCmd ""))
(StmtCmd (LetStmt (ArgLValue (VarArgument y)) (FloatExpr 0)))
(ShowCmd (CallExpr U))
(PrintCmd "")
(StmtCmd (ReturnStmt (VarExpr w)))
