(PrintCmd "")
(ShowCmd (FloatExpr 72626))
(WriteImageCmd (VarExpr D5C_) "")
(ShowCmd (FloatExpr 2))
(ShowCmd (IntExpr 40))
(TimeCmd (WriteImageCmd (FloatExpr 56) ""))
(StmtCmd (ReturnStmt (IntExpr 16841)))
(PrintCmd "")
(WriteImageCmd (IntExpr 1) "v")
(StmtCmd (LetStmt (ArgLValue (VarArgument E8r.7g.5u.)) (FloatExpr 589)))
(TimeCmd (WriteImageCmd (VarExpr D6C.) "$"))
(PrintCmd "")
(StmtCmd (ReturnStmt (FloatExpr 8)))
(ShowCmd (CallExpr g0z_6l.8u.2m.1T.))
(PrintCmd "o|nm.D")
(WriteImageCmd (VarExpr Q8c.2V_) "z")
(ReadImageCmd "" (VarArgument O))
