(TimeCmd (PrintCmd "R"))
(TimeCmd (WriteImageCmd (FloatExpr 84999) "lq"))
(ShowCmd (FloatExpr 6213452302100))
(WriteImageCmd (FloatExpr 0) "o")
(StmtCmd (AssertStmt (IntExpr 0) ""))
(TimeCmd (ReadImageCmd "2" (VarArgument t)))
(ShowCmd (FloatExpr 0))
(PrintCmd "")
(TimeCmd (TimeCmd (WriteImageCmd (CallExpr P) "")))
