#!/usr/bin/env perl

use strict;
use autodie;
use warnings;
use File::Spec;

#my $compiler = $ARGV[0];
#die "please specify a compiler" unless defined $compiler;
#die unless -x $compiler;

my $exe = File::Spec->rel2abs($0);
die unless ($exe =~ /^(.*)\/test-parser$/);
my $dir = "${1}/parser-tests";
#print "$dir\n";
die unless -d $dir;

my @files = glob "${dir}/*.jpl";

sub runit($) {
    (my $cmd) = @_;
    open my $INF, "$cmd |" or die;
    my $good = 0;
    my $bad = 0;
    while (my $line = <$INF>) {
        $good++ if ($line =~ /Compilation succeeded/);
        $bad++ if ($line =~ /Compilation failed/);
    }
    return 2 if (($good + $bad) != 1);
    return 1 if ($bad == 1);
    return 0 if ($good == 1);
    die "whoops!";
}

sub lookat($) {
    (my $f) = @_;
    my $ok = 0;
    my $error = 0;
    open my $INF, "<$f" or die;
    while (my $line = <$INF>) {
        if ($line =~ /^\/\/ OK$/) {
            $ok = 1;
        }
        if ($line =~ /^\/\/ ERROR$/) {
            $error = 1;
        }
    }
    close $INF;
    die "bogus test case '$f'" unless ($ok + $error) == 1;
    return $error;
}

sub pr($) {
    (my $x) = @_;
    return ($x == 0) ? "OK   " : "ERROR";
}

my $fails = 0;

foreach my $f (@files) {
    my $expect = lookat($f);

    my $got = runit("make run-a5p TEST=$f");
    
    print "$f : expect = ".pr($expect).", got = ".pr($got);
    if ($got != $expect) {
        print "    <----------------- OOPS";
        $fails++;
    }
    print "\n";
}

print "\n";

if ($fails == 0) {
    print "All tests pass.\n";
} else {
    print "${fails} tests fail.\n";
}

